# Generated by Django 4.2.4 on 2023-08-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('cik', models.IntegerField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fund_info',
                'managed': False,
            },
        ),
    ]
