# Generated by Django 4.2.4 on 2023-08-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('infotable_sk', models.IntegerField(primary_key=True, serialize=False)),
                ('accession_number', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('filing_period', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'position_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityInfo',
            fields=[
                ('cusip', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('ticker', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_class', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'security_info',
                'managed': False,
            },
        ),
    ]
